# Generated by Django 5.2.14 on 2026-05-17 05:28

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('kind', models.CharField(choices=[('announcement', 'Announcement'), ('flyer', 'Flyer'), ('fundraiser', 'Fundraiser'), ('spirit', 'Spirit Wear'), ('reminder', 'Reminder')], default='announcement', max_length=20)),
                ('short_text', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='announcements/')),
                ('file', models.FileField(blank=True, upload_to='announcements/files/')),
                ('cta_url', models.URLField(blank=True)),
                ('publish_date', models.DateField()),
                ('expires_date', models.DateField(blank=True, null=True)),
                ('published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-publish_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='DonationCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('goal_amount', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('current_amount', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('stripe_payment_link', models.URLField(help_text='Use a Stripe Payment Link, e.g. https://buy.stripe.com/...')),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('category', models.CharField(choices=[('family', 'Family Event'), ('pta', 'PTA Meeting'), ('fundraiser', 'Fundraiser'), ('spirit', 'Spirit Day'), ('appreciation', 'Teacher Appreciation'), ('other', 'Other')], default='family', max_length=20)),
                ('short_description', models.CharField(blank=True, max_length=240)),
                ('description', models.TextField(blank=True)),
                ('flyer', models.FileField(blank=True, upload_to='events/')),
                ('cta_label', models.CharField(blank=True, default='Learn more', max_length=80)),
                ('cta_url', models.URLField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='NewsletterIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('issue_date', models.DateField(help_text='Used for ordering. Latest appears first.')),
                ('summary', models.TextField(blank=True)),
                ('cover_image', models.ImageField(blank=True, upload_to='newsletters/covers/')),
                ('pdf', models.FileField(blank=True, upload_to='newsletters/files/')),
                ('external_url', models.URLField(blank=True)),
                ('published', models.BooleanField(default=True)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-issue_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pta_name', models.CharField(default='Cox Elementary PTA', max_length=120)),
                ('school_name', models.CharField(default='Cox Elementary School', max_length=120)),
                ('tagline', models.CharField(default='Building Community, Supporting Students, Strengthening Our School', max_length=180)),
                ('hero_message', models.TextField(default='A warm, organized hub for events, newsletters, volunteer opportunities, fundraising, and family resources.')),
                ('contact_email', models.EmailField(default='pta@coxelementary.org', max_length=254)),
                ('instagram_url', models.URLField(blank=True)),
                ('linktree_url', models.URLField(blank=True)),
                ('school_contact_url', models.URLField(blank=True)),
                ('lunch_menu_url', models.URLField(blank=True)),
                ('attendance_url', models.URLField(blank=True)),
                ('spirit_wear_url', models.URLField(blank=True)),
                ('calendar_url', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='site/')),
                ('mascot', models.ImageField(blank=True, upload_to='site/')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=160)),
                ('logo', models.ImageField(blank=True, upload_to='sponsors/')),
                ('website', models.URLField(blank=True)),
                ('level', models.CharField(blank=True, max_length=80)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VolunteerOpportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=160)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('time_commitment', models.CharField(blank=True, max_length=80)),
                ('committee', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField()),
                ('active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Volunteer opportunities',
                'ordering': ['sort_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('student_grade', models.CharField(blank=True, max_length=40)),
                ('message', models.TextField(blank=True)),
                ('reviewed', models.BooleanField(default=False)),
                ('opportunity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pta.volunteeropportunity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
