# Generated by Django 5.2.14 on 2026-05-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='image_content_type',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image_filename',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
