# Generated by Django 5.2.14 on 2026-05-17 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pta', '0002_announcement_image_content_type_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletterissue',
            options={'ordering': ['-issue_date', '-created_at'], 'verbose_name': 'Newsletter', 'verbose_name_plural': 'Newsletters'},
        ),
    ]
