# Generated by Django 5.2.14 on 2026-05-17 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pta', '0003_alter_newsletterissue_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsletterissue',
            name='cover_image_content_type',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='newsletterissue',
            name='cover_image_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='newsletterissue',
            name='cover_image_filename',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
