# Generated by Django 5.2.14 on 2026-05-17 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pta', '0004_newsletterissue_cover_image_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='logo_content_type',
            field=models.CharField(blank=True, editable=False, max_length=80),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='logo_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='logo_filename',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
