# Generated by Django 5.2.14 on 2026-05-17 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pta', '0005_sponsor_logo_content_type_sponsor_logo_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='membership_fee',
            field=models.DecimalField(decimal_places=2, default=15.0, help_text='Flat PTA membership amount shown on the Join PTA page.', max_digits=6),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='membership_payment_link',
            field=models.URLField(blank=True, help_text='Paste the Stripe Payment Link or checkout URL for the $15 PTA membership.'),
        ),
    ]
